"""
Django settings for portfolio_project project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%hsb8la0y4i9feke(=zszz!0%6!&wxor39rh)mms(w5$a87p7o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '10.251.121.180', '.onrender.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'portfolio',
    'jazzmin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portfolio_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# portfolio_project/settings.py

# Base url to serve media files
MEDIA_URL = '/media/'

# Path where media files are stored on your computer

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Add this at the absolute bottom of settings.py
STATIC_ROOT = BASE_DIR / 'staticfiles'

JAZZMIN_SETTINGS = {
    # Title on the browser tab
    "site_title": "Ekanem Bassey Admin",
    
    # Title on the brand header screen
    "site_header": "EBTech Engine",
    
    # Brand logo text (Top left corner)
    "site_brand": "EBTech_ Backend",
    
    # Welcome text on the login screen
    "welcome_sign": "Welcome back, Director. Accessing Secure Portfolio Database...",
    
    # Copyright on the footer layout
    "copyright": "Ekanem Bassey Portfolio Ltd",
    
    # Top Menu Links
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Live Site", "url": "/", "new_window": True},
    ],

    # User Menu Link icon customization
    "user_avatar": None,

    #############
    # Side Menu Custom Icons (Using FontAwesome)
    #############
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user-shield",
        "auth.group": "fas fa-users",
        "portfolio.BlogPost": "fas fa-newspaper",  # Custom icon for blogs
        "portfolio.Task": "fas fa-tasks",          # Custom icon for tasks
    },
    
    # Layout Tweaks
    "show_sidebar": True,
    "navigation_expanded": True,
    "changeform_format": "horizontal_tabs",
}

# 🎨 THEME CUSTOMIZATION (Dark Mode & Professional Accent Colors)
JAZZMIN_UI_CHANGES = {
    "theme": "darkly",              # Clean, dark mode base theme
    "dark_mode_theme": "darkly",    # Ensures dark mode stays locked in
    "navbar": "navbar-dark navbar-primary", # Primary accent highlight on top navbar
    "sidebar": "sidebar-dark-primary",      # Matching sidebar accents
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "success": "btn-success",
        "warning": "btn-warning",
        "danger": "btn-danger"
    }
}